### ISSUE TITLE
Traefik container need to create certs/acme.json file

### ISSUE THREAD

**Issue by minump** [Diamond-Proj/diamond-admin-dashboard#4]
Have the docker-compose.yaml file create a certs/acme.json file in traefik container. this needs to be with 600 permission.

Currently, the developer manually creates a certs/acme.json file (`touch certs/acme.json`) in the repo base folder (diamond-admin-dashboard). This is mounted as a volume in the traefik container. 
Tried with the below docker-compose.yaml file `traefik service`. The build succeeded, but the traefik container did not start. No container logs where present. It did not throw any runtime error as well.

```
traefik:
    image: traefik:v3.1
    entrypoint: >
      /bin/sh -c "
      mkdir -p /certs &&
      touch /certs/acme.json &&
      chmod 600 /certs/acme.json &&
      /entrypoint.sh traefik
      "
    command:
      - --log.level=DEBUG
      - --api
      # Entrypoints
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      # Activate tls entrypoint resolver
      - --entrypoints.https.http.tls.certresolver=myresolver
      # letsencrypt
      - --certificatesresolvers.myresolver.acme.email=diamond-project@lists.ncsa.illinois.edu
      - --certificatesresolvers.myresolver.acme.storage=/certs/acme.json
      # uncomment to use testing certs
      # - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=http
      # Enabling docker providers
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch=true
    restart: unless-stopped
    ports:
      - "${TRAEFIK_HTTP_PORT:-8000}:80"
      - "${TRAEFIK_HTTPS_PORT:-8443}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker daemon socket
    networks:
      - diamond-frontend-network
    labels:
      - "traefik.enable=true"
      # change Host to traefik.diamond.ncsa.illinois.edu in Prod and traefik.localhost in Local
      - "traefik.http.routers.traefik.rule=Host(`traefik.diamond.ncsa.illinois.edu`)"  # Dashboard
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
```

The main change between the original and the above is the entrypoint script and the removal of the certs volume mount.
